# Generated by Django 4.0.4 on 2022-05-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_book_author'),
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='book',
            field=models.ManyToManyField(null=True, to='home.book'),
        ),
    ]
