# Generated by Django 4.0.4 on 2022-05-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_book_author'),
        ('favorites', '0003_rename_book_favorites_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='books',
            field=models.ManyToManyField(to='home.book'),
        ),
    ]
